on: [push, pull_request]
name: test
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Currently, actions/setup-go does not set GOTOOLCHAIN to "local",
      # necessary to avoid the toolchain auto-updating to the version in go.mod.
      # cf. https://github.com/actions/setup-go/issues/491
      GOTOOLCHAIN: local
    strategy:
      fail-fast: false
      matrix:
        go: ["stable"]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Test
        run: go test -race ./...
